### ISSUE TITLE
Authorization doesn't work; 108 Invalid frob

### ISSUE THREAD

**Issue by rudolphos** [magnusvk/FlickrFaves#6]
Authorization doesn't work, it redirects to flickr main page.

![image](https://user-images.githubusercontent.com/4366810/28324424-042e2056-6be4-11e7-9009-a16d0d4ec44b.png)

A flickr API call failed with the following message: 108: Invalid frob

```
An error has occured within FlickrFaves 2.0.6 (build #21).

STACKTRACE:
com.aetrion.flickr.FlickrException: 108: Invalid frob
	at com.aetrion.flickr.auth.AuthInterface.getToken(AuthInterface.java:182)
	at de.vonkoeller.flickrFaves.api.Authentication.getAuth(Authentication.java:82)
	at de.vonkoeller.flickrFaves.gui.FlickrFaves.completeAuth(FlickrFaves.java:254)
	at de.vonkoeller.flickrFaves.gui.FlickrFaves.actionPerformed(FlickrFaves.java:663)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

DEBUG LOG:
Tue Jul 18 18:06:57 EEST 2017: Starting up...
Tue Jul 18 18:06:57 EEST 2017: Checking authorization...
Tue Jul 18 18:06:57 EEST 2017: Now doing the version check...
Tue Jul 18 18:06:57 EEST 2017: Latest version is 2.0.6, build #21...
Tue Jul 18 18:06:57 EEST 2017: No auth token available, get one now...
```

**Comment by magnusvk** [comment]
Yes, this is a known issue. I don't use FlickrFaves anymore and don't have the time to fix. Would you be able to work on fixing this? I'd be very happy to look at a pull request.

See unmaintained notice here: https://github.com/magnusvk/FlickrFaves#unmaintained
